/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BibleSummaryCountriesInner } from './BibleSummaryCountriesInner';
import {
    BibleSummaryCountriesInnerFromJSON,
    BibleSummaryCountriesInnerFromJSONTyped,
    BibleSummaryCountriesInnerToJSON,
    BibleSummaryCountriesInnerToJSONTyped,
} from './BibleSummaryCountriesInner';
import type { Language } from './Language';
import {
    LanguageFromJSON,
    LanguageFromJSONTyped,
    LanguageToJSON,
    LanguageToJSONTyped,
} from './Language';

/**
 * 
 * @export
 * @interface AudioBible
 */
export interface AudioBible {
    /**
     * 
     * @type {string}
     * @memberof AudioBible
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AudioBible
     */
    dblId: string;
    /**
     * 
     * @type {string}
     * @memberof AudioBible
     */
    abbreviation: string;
    /**
     * 
     * @type {string}
     * @memberof AudioBible
     */
    abbreviationLocal: string;
    /**
     * 
     * @type {string}
     * @memberof AudioBible
     */
    copyright: string;
    /**
     * 
     * @type {Language}
     * @memberof AudioBible
     */
    language: Language;
    /**
     * 
     * @type {Array<BibleSummaryCountriesInner>}
     * @memberof AudioBible
     */
    countries: Array<BibleSummaryCountriesInner>;
    /**
     * 
     * @type {string}
     * @memberof AudioBible
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AudioBible
     */
    nameLocal: string;
    /**
     * 
     * @type {string}
     * @memberof AudioBible
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof AudioBible
     */
    descriptionLocal: string;
    /**
     * 
     * @type {string}
     * @memberof AudioBible
     */
    info: string;
    /**
     * 
     * @type {string}
     * @memberof AudioBible
     */
    type: string;
    /**
     * 
     * @type {Date}
     * @memberof AudioBible
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof AudioBible
     */
    relatedDbl: string;
}

/**
 * Check if a given object implements the AudioBible interface.
 */
export function instanceOfAudioBible(value: object): value is AudioBible {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('dblId' in value) || value['dblId'] === undefined) return false;
    if (!('abbreviation' in value) || value['abbreviation'] === undefined) return false;
    if (!('abbreviationLocal' in value) || value['abbreviationLocal'] === undefined) return false;
    if (!('copyright' in value) || value['copyright'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('countries' in value) || value['countries'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('nameLocal' in value) || value['nameLocal'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('descriptionLocal' in value) || value['descriptionLocal'] === undefined) return false;
    if (!('info' in value) || value['info'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('relatedDbl' in value) || value['relatedDbl'] === undefined) return false;
    return true;
}

export function AudioBibleFromJSON(json: any): AudioBible {
    return AudioBibleFromJSONTyped(json, false);
}

export function AudioBibleFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioBible {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'dblId': json['dblId'],
        'abbreviation': json['abbreviation'],
        'abbreviationLocal': json['abbreviationLocal'],
        'copyright': json['copyright'],
        'language': LanguageFromJSON(json['language']),
        'countries': ((json['countries'] as Array<any>).map(BibleSummaryCountriesInnerFromJSON)),
        'name': json['name'],
        'nameLocal': json['nameLocal'],
        'description': json['description'],
        'descriptionLocal': json['descriptionLocal'],
        'info': json['info'],
        'type': json['type'],
        'updatedAt': (new Date(json['updatedAt'])),
        'relatedDbl': json['relatedDbl'],
    };
}

export function AudioBibleToJSON(json: any): AudioBible {
    return AudioBibleToJSONTyped(json, false);
}

export function AudioBibleToJSONTyped(value?: AudioBible | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'dblId': value['dblId'],
        'abbreviation': value['abbreviation'],
        'abbreviationLocal': value['abbreviationLocal'],
        'copyright': value['copyright'],
        'language': LanguageToJSON(value['language']),
        'countries': ((value['countries'] as Array<any>).map(BibleSummaryCountriesInnerToJSON)),
        'name': value['name'],
        'nameLocal': value['nameLocal'],
        'description': value['description'],
        'descriptionLocal': value['descriptionLocal'],
        'info': value['info'],
        'type': value['type'],
        'updatedAt': ((value['updatedAt']).toISOString()),
        'relatedDbl': value['relatedDbl'],
    };
}

