/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AudioChapterTimecodesInner
 */
export interface AudioChapterTimecodesInner {
    /**
     * 
     * @type {string}
     * @memberof AudioChapterTimecodesInner
     */
    end: string;
    /**
     * 
     * @type {string}
     * @memberof AudioChapterTimecodesInner
     */
    start: string;
    /**
     * 
     * @type {string}
     * @memberof AudioChapterTimecodesInner
     */
    verseId: string;
}

/**
 * Check if a given object implements the AudioChapterTimecodesInner interface.
 */
export function instanceOfAudioChapterTimecodesInner(value: object): value is AudioChapterTimecodesInner {
    if (!('end' in value) || value['end'] === undefined) return false;
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('verseId' in value) || value['verseId'] === undefined) return false;
    return true;
}

export function AudioChapterTimecodesInnerFromJSON(json: any): AudioChapterTimecodesInner {
    return AudioChapterTimecodesInnerFromJSONTyped(json, false);
}

export function AudioChapterTimecodesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioChapterTimecodesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'end': json['end'],
        'start': json['start'],
        'verseId': json['verseId'],
    };
}

export function AudioChapterTimecodesInnerToJSON(json: any): AudioChapterTimecodesInner {
    return AudioChapterTimecodesInnerToJSONTyped(json, false);
}

export function AudioChapterTimecodesInnerToJSONTyped(value?: AudioChapterTimecodesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end': value['end'],
        'start': value['start'],
        'verseId': value['verseId'],
    };
}

