/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChapterNext } from './ChapterNext';
import {
    ChapterNextFromJSON,
    ChapterNextFromJSONTyped,
    ChapterNextToJSON,
    ChapterNextToJSONTyped,
} from './ChapterNext';
import type { AudioChapterTimecodesInner } from './AudioChapterTimecodesInner';
import {
    AudioChapterTimecodesInnerFromJSON,
    AudioChapterTimecodesInnerFromJSONTyped,
    AudioChapterTimecodesInnerToJSON,
    AudioChapterTimecodesInnerToJSONTyped,
} from './AudioChapterTimecodesInner';

/**
 * 
 * @export
 * @interface AudioChapter
 */
export interface AudioChapter {
    /**
     * 
     * @type {string}
     * @memberof AudioChapter
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AudioChapter
     */
    bibleId: string;
    /**
     * 
     * @type {string}
     * @memberof AudioChapter
     */
    number: string;
    /**
     * 
     * @type {string}
     * @memberof AudioChapter
     */
    bookId: string;
    /**
     * 
     * @type {string}
     * @memberof AudioChapter
     */
    resourceUrl: string;
    /**
     * 
     * @type {Array<AudioChapterTimecodesInner>}
     * @memberof AudioChapter
     */
    timecodes?: Array<AudioChapterTimecodesInner>;
    /**
     * 
     * @type {number}
     * @memberof AudioChapter
     */
    expiresAt: number;
    /**
     * 
     * @type {string}
     * @memberof AudioChapter
     */
    reference: string;
    /**
     * 
     * @type {ChapterNext}
     * @memberof AudioChapter
     */
    next?: ChapterNext;
    /**
     * 
     * @type {ChapterNext}
     * @memberof AudioChapter
     */
    previous?: ChapterNext;
    /**
     * 
     * @type {string}
     * @memberof AudioChapter
     */
    copyright?: string;
}

/**
 * Check if a given object implements the AudioChapter interface.
 */
export function instanceOfAudioChapter(value: object): value is AudioChapter {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('bibleId' in value) || value['bibleId'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    if (!('resourceUrl' in value) || value['resourceUrl'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('reference' in value) || value['reference'] === undefined) return false;
    return true;
}

export function AudioChapterFromJSON(json: any): AudioChapter {
    return AudioChapterFromJSONTyped(json, false);
}

export function AudioChapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioChapter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bibleId': json['bibleId'],
        'number': json['number'],
        'bookId': json['bookId'],
        'resourceUrl': json['resourceUrl'],
        'timecodes': json['timecodes'] == null ? undefined : ((json['timecodes'] as Array<any>).map(AudioChapterTimecodesInnerFromJSON)),
        'expiresAt': json['expiresAt'],
        'reference': json['reference'],
        'next': json['next'] == null ? undefined : ChapterNextFromJSON(json['next']),
        'previous': json['previous'] == null ? undefined : ChapterNextFromJSON(json['previous']),
        'copyright': json['copyright'] == null ? undefined : json['copyright'],
    };
}

export function AudioChapterToJSON(json: any): AudioChapter {
    return AudioChapterToJSONTyped(json, false);
}

export function AudioChapterToJSONTyped(value?: AudioChapter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bibleId': value['bibleId'],
        'number': value['number'],
        'bookId': value['bookId'],
        'resourceUrl': value['resourceUrl'],
        'timecodes': value['timecodes'] == null ? undefined : ((value['timecodes'] as Array<any>).map(AudioChapterTimecodesInnerToJSON)),
        'expiresAt': value['expiresAt'],
        'reference': value['reference'],
        'next': ChapterNextToJSON(value['next']),
        'previous': ChapterNextToJSON(value['previous']),
        'copyright': value['copyright'],
    };
}

