/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AudioBibleSummary
 */
export interface AudioBibleSummary {
    /**
     * 
     * @type {string}
     * @memberof AudioBibleSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AudioBibleSummary
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AudioBibleSummary
     */
    nameLocal: string;
    /**
     * 
     * @type {string}
     * @memberof AudioBibleSummary
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof AudioBibleSummary
     */
    descriptionLocal: string;
}

/**
 * Check if a given object implements the AudioBibleSummary interface.
 */
export function instanceOfAudioBibleSummary(value: object): value is AudioBibleSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('nameLocal' in value) || value['nameLocal'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('descriptionLocal' in value) || value['descriptionLocal'] === undefined) return false;
    return true;
}

export function AudioBibleSummaryFromJSON(json: any): AudioBibleSummary {
    return AudioBibleSummaryFromJSONTyped(json, false);
}

export function AudioBibleSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioBibleSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'nameLocal': json['nameLocal'],
        'description': json['description'],
        'descriptionLocal': json['descriptionLocal'],
    };
}

export function AudioBibleSummaryToJSON(json: any): AudioBibleSummary {
    return AudioBibleSummaryToJSONTyped(json, false);
}

export function AudioBibleSummaryToJSONTyped(value?: AudioBibleSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'nameLocal': value['nameLocal'],
        'description': value['description'],
        'descriptionLocal': value['descriptionLocal'],
    };
}

