/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BibleSummaryCountriesInner
 */
export interface BibleSummaryCountriesInner {
    /**
     * 
     * @type {string}
     * @memberof BibleSummaryCountriesInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BibleSummaryCountriesInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BibleSummaryCountriesInner
     */
    nameLocal: string;
}

/**
 * Check if a given object implements the BibleSummaryCountriesInner interface.
 */
export function instanceOfBibleSummaryCountriesInner(value: object): value is BibleSummaryCountriesInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('nameLocal' in value) || value['nameLocal'] === undefined) return false;
    return true;
}

export function BibleSummaryCountriesInnerFromJSON(json: any): BibleSummaryCountriesInner {
    return BibleSummaryCountriesInnerFromJSONTyped(json, false);
}

export function BibleSummaryCountriesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BibleSummaryCountriesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'nameLocal': json['nameLocal'],
    };
}

export function BibleSummaryCountriesInnerToJSON(json: any): BibleSummaryCountriesInner {
    return BibleSummaryCountriesInnerToJSONTyped(json, false);
}

export function BibleSummaryCountriesInnerToJSONTyped(value?: BibleSummaryCountriesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'nameLocal': value['nameLocal'],
    };
}

