/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChapterNext } from './ChapterNext';
import {
    ChapterNextFromJSON,
    ChapterNextFromJSONTyped,
    ChapterNextToJSON,
    ChapterNextToJSONTyped,
} from './ChapterNext';

/**
 * 
 * @export
 * @interface Chapter
 */
export interface Chapter {
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    bibleId: string;
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    number: string;
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    bookId: string;
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    reference: string;
    /**
     * 
     * @type {number}
     * @memberof Chapter
     */
    verseCount: number;
    /**
     * 
     * @type {ChapterNext}
     * @memberof Chapter
     */
    next?: ChapterNext;
    /**
     * 
     * @type {ChapterNext}
     * @memberof Chapter
     */
    previous?: ChapterNext;
    /**
     * 
     * @type {string}
     * @memberof Chapter
     */
    copyright: string;
}

/**
 * Check if a given object implements the Chapter interface.
 */
export function instanceOfChapter(value: object): value is Chapter {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('bibleId' in value) || value['bibleId'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('reference' in value) || value['reference'] === undefined) return false;
    if (!('verseCount' in value) || value['verseCount'] === undefined) return false;
    if (!('copyright' in value) || value['copyright'] === undefined) return false;
    return true;
}

export function ChapterFromJSON(json: any): Chapter {
    return ChapterFromJSONTyped(json, false);
}

export function ChapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Chapter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bibleId': json['bibleId'],
        'number': json['number'],
        'bookId': json['bookId'],
        'content': json['content'],
        'reference': json['reference'],
        'verseCount': json['verseCount'],
        'next': json['next'] == null ? undefined : ChapterNextFromJSON(json['next']),
        'previous': json['previous'] == null ? undefined : ChapterNextFromJSON(json['previous']),
        'copyright': json['copyright'],
    };
}

export function ChapterToJSON(json: any): Chapter {
    return ChapterToJSONTyped(json, false);
}

export function ChapterToJSONTyped(value?: Chapter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bibleId': value['bibleId'],
        'number': value['number'],
        'bookId': value['bookId'],
        'content': value['content'],
        'reference': value['reference'],
        'verseCount': value['verseCount'],
        'next': ChapterNextToJSON(value['next']),
        'previous': ChapterNextToJSON(value['previous']),
        'copyright': value['copyright'],
    };
}

