/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChapterSummary
 */
export interface ChapterSummary {
    /**
     * 
     * @type {string}
     * @memberof ChapterSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ChapterSummary
     */
    bibleId: string;
    /**
     * 
     * @type {string}
     * @memberof ChapterSummary
     */
    number: string;
    /**
     * 
     * @type {string}
     * @memberof ChapterSummary
     */
    bookId: string;
    /**
     * 
     * @type {string}
     * @memberof ChapterSummary
     */
    reference: string;
}

/**
 * Check if a given object implements the ChapterSummary interface.
 */
export function instanceOfChapterSummary(value: object): value is ChapterSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('bibleId' in value) || value['bibleId'] === undefined) return false;
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    if (!('reference' in value) || value['reference'] === undefined) return false;
    return true;
}

export function ChapterSummaryFromJSON(json: any): ChapterSummary {
    return ChapterSummaryFromJSONTyped(json, false);
}

export function ChapterSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bibleId': json['bibleId'],
        'number': json['number'],
        'bookId': json['bookId'],
        'reference': json['reference'],
    };
}

export function ChapterSummaryToJSON(json: any): ChapterSummary {
    return ChapterSummaryToJSONTyped(json, false);
}

export function ChapterSummaryToJSONTyped(value?: ChapterSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bibleId': value['bibleId'],
        'number': value['number'],
        'bookId': value['bookId'],
        'reference': value['reference'],
    };
}

