/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChapterNext
 */
export interface ChapterNext {
    /**
     * 
     * @type {string}
     * @memberof ChapterNext
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ChapterNext
     */
    bookId?: string;
    /**
     * 
     * @type {string}
     * @memberof ChapterNext
     */
    number?: string;
}

/**
 * Check if a given object implements the ChapterNext interface.
 */
export function instanceOfChapterNext(value: object): value is ChapterNext {
    return true;
}

export function ChapterNextFromJSON(json: any): ChapterNext {
    return ChapterNextFromJSONTyped(json, false);
}

export function ChapterNextFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterNext {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'bookId': json['bookId'] == null ? undefined : json['bookId'],
        'number': json['number'] == null ? undefined : json['number'],
    };
}

export function ChapterNextToJSON(json: any): ChapterNext {
    return ChapterNextToJSONTyped(json, false);
}

export function ChapterNextToJSONTyped(value?: ChapterNext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bookId': value['bookId'],
        'number': value['number'],
    };
}

