/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { AudioChapter } from './AudioChapter';
import {
    AudioChapterFromJSON,
    AudioChapterFromJSONTyped,
    AudioChapterToJSON,
    AudioChapterToJSONTyped,
} from './AudioChapter';

/**
 * 
 * @export
 * @interface GetAudioChapter200Response
 */
export interface GetAudioChapter200Response {
    /**
     * 
     * @type {AudioChapter}
     * @memberof GetAudioChapter200Response
     */
    data: AudioChapter;
    /**
     * 
     * @type {Meta}
     * @memberof GetAudioChapter200Response
     */
    meta: Meta;
}

/**
 * Check if a given object implements the GetAudioChapter200Response interface.
 */
export function instanceOfGetAudioChapter200Response(value: object): value is GetAudioChapter200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function GetAudioChapter200ResponseFromJSON(json: any): GetAudioChapter200Response {
    return GetAudioChapter200ResponseFromJSONTyped(json, false);
}

export function GetAudioChapter200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAudioChapter200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AudioChapterFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
    };
}

export function GetAudioChapter200ResponseToJSON(json: any): GetAudioChapter200Response {
    return GetAudioChapter200ResponseToJSONTyped(json, false);
}

export function GetAudioChapter200ResponseToJSONTyped(value?: GetAudioChapter200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AudioChapterToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
    };
}

