/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AudioBible } from './AudioBible';
import {
    AudioBibleFromJSON,
    AudioBibleFromJSONTyped,
    AudioBibleToJSON,
    AudioBibleToJSONTyped,
} from './AudioBible';

/**
 * 
 * @export
 * @interface GetAudioBible200Response
 */
export interface GetAudioBible200Response {
    /**
     * 
     * @type {AudioBible}
     * @memberof GetAudioBible200Response
     */
    data: AudioBible;
}

/**
 * Check if a given object implements the GetAudioBible200Response interface.
 */
export function instanceOfGetAudioBible200Response(value: object): value is GetAudioBible200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetAudioBible200ResponseFromJSON(json: any): GetAudioBible200Response {
    return GetAudioBible200ResponseFromJSONTyped(json, false);
}

export function GetAudioBible200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAudioBible200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AudioBibleFromJSON(json['data']),
    };
}

export function GetAudioBible200ResponseToJSON(json: any): GetAudioBible200Response {
    return GetAudioBible200ResponseToJSONTyped(json, false);
}

export function GetAudioBible200ResponseToJSONTyped(value?: GetAudioBible200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AudioBibleToJSON(value['data']),
    };
}

