/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BibleSummary } from './BibleSummary';
import {
    BibleSummaryFromJSON,
    BibleSummaryFromJSONTyped,
    BibleSummaryToJSON,
    BibleSummaryToJSONTyped,
} from './BibleSummary';

/**
 * 
 * @export
 * @interface GetBibles200Response
 */
export interface GetBibles200Response {
    /**
     * 
     * @type {Array<BibleSummary>}
     * @memberof GetBibles200Response
     */
    data: Array<BibleSummary>;
}

/**
 * Check if a given object implements the GetBibles200Response interface.
 */
export function instanceOfGetBibles200Response(value: object): value is GetBibles200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetBibles200ResponseFromJSON(json: any): GetBibles200Response {
    return GetBibles200ResponseFromJSONTyped(json, false);
}

export function GetBibles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBibles200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(BibleSummaryFromJSON)),
    };
}

export function GetBibles200ResponseToJSON(json: any): GetBibles200Response {
    return GetBibles200ResponseToJSONTyped(json, false);
}

export function GetBibles200ResponseToJSONTyped(value?: GetBibles200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(BibleSummaryToJSON)),
    };
}

