/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SectionSummary } from './SectionSummary';
import {
    SectionSummaryFromJSON,
    SectionSummaryFromJSONTyped,
    SectionSummaryToJSON,
    SectionSummaryToJSONTyped,
} from './SectionSummary';

/**
 * 
 * @export
 * @interface GetBookSections200Response
 */
export interface GetBookSections200Response {
    /**
     * 
     * @type {Array<SectionSummary>}
     * @memberof GetBookSections200Response
     */
    data: Array<SectionSummary>;
}

/**
 * Check if a given object implements the GetBookSections200Response interface.
 */
export function instanceOfGetBookSections200Response(value: object): value is GetBookSections200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetBookSections200ResponseFromJSON(json: any): GetBookSections200Response {
    return GetBookSections200ResponseFromJSONTyped(json, false);
}

export function GetBookSections200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBookSections200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(SectionSummaryFromJSON)),
    };
}

export function GetBookSections200ResponseToJSON(json: any): GetBookSections200Response {
    return GetBookSections200ResponseToJSONTyped(json, false);
}

export function GetBookSections200ResponseToJSONTyped(value?: GetBookSections200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(SectionSummaryToJSON)),
    };
}

