/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bible } from './Bible';
import {
    BibleFromJSON,
    BibleFromJSONTyped,
    BibleToJSON,
    BibleToJSONTyped,
} from './Bible';

/**
 * 
 * @export
 * @interface GetBible200Response
 */
export interface GetBible200Response {
    /**
     * 
     * @type {Bible}
     * @memberof GetBible200Response
     */
    data: Bible;
}

/**
 * Check if a given object implements the GetBible200Response interface.
 */
export function instanceOfGetBible200Response(value: object): value is GetBible200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetBible200ResponseFromJSON(json: any): GetBible200Response {
    return GetBible200ResponseFromJSONTyped(json, false);
}

export function GetBible200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBible200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': BibleFromJSON(json['data']),
    };
}

export function GetBible200ResponseToJSON(json: any): GetBible200Response {
    return GetBible200ResponseToJSONTyped(json, false);
}

export function GetBible200ResponseToJSONTyped(value?: GetBible200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': BibleToJSON(value['data']),
    };
}

