/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Book } from './Book';
import {
    BookFromJSON,
    BookFromJSONTyped,
    BookToJSON,
    BookToJSONTyped,
} from './Book';

/**
 * 
 * @export
 * @interface GetBook200Response
 */
export interface GetBook200Response {
    /**
     * 
     * @type {Book}
     * @memberof GetBook200Response
     */
    data: Book;
}

/**
 * Check if a given object implements the GetBook200Response interface.
 */
export function instanceOfGetBook200Response(value: object): value is GetBook200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetBook200ResponseFromJSON(json: any): GetBook200Response {
    return GetBook200ResponseFromJSONTyped(json, false);
}

export function GetBook200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBook200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': BookFromJSON(json['data']),
    };
}

export function GetBook200ResponseToJSON(json: any): GetBook200Response {
    return GetBook200ResponseToJSONTyped(json, false);
}

export function GetBook200ResponseToJSONTyped(value?: GetBook200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': BookToJSON(value['data']),
    };
}

