/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Book } from './Book';
import {
    BookFromJSON,
    BookFromJSONTyped,
    BookToJSON,
    BookToJSONTyped,
} from './Book';

/**
 * 
 * @export
 * @interface GetBooks200Response
 */
export interface GetBooks200Response {
    /**
     * 
     * @type {Array<Book>}
     * @memberof GetBooks200Response
     */
    data: Array<Book>;
}

/**
 * Check if a given object implements the GetBooks200Response interface.
 */
export function instanceOfGetBooks200Response(value: object): value is GetBooks200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetBooks200ResponseFromJSON(json: any): GetBooks200Response {
    return GetBooks200ResponseFromJSONTyped(json, false);
}

export function GetBooks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBooks200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(BookFromJSON)),
    };
}

export function GetBooks200ResponseToJSON(json: any): GetBooks200Response {
    return GetBooks200ResponseToJSONTyped(json, false);
}

export function GetBooks200ResponseToJSONTyped(value?: GetBooks200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(BookToJSON)),
    };
}

