/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChapterSummary } from './ChapterSummary';
import {
    ChapterSummaryFromJSON,
    ChapterSummaryFromJSONTyped,
    ChapterSummaryToJSON,
    ChapterSummaryToJSONTyped,
} from './ChapterSummary';

/**
 * 
 * @export
 * @interface GetChapters200Response
 */
export interface GetChapters200Response {
    /**
     * 
     * @type {Array<ChapterSummary>}
     * @memberof GetChapters200Response
     */
    data: Array<ChapterSummary>;
}

/**
 * Check if a given object implements the GetChapters200Response interface.
 */
export function instanceOfGetChapters200Response(value: object): value is GetChapters200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetChapters200ResponseFromJSON(json: any): GetChapters200Response {
    return GetChapters200ResponseFromJSONTyped(json, false);
}

export function GetChapters200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetChapters200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ChapterSummaryFromJSON)),
    };
}

export function GetChapters200ResponseToJSON(json: any): GetChapters200Response {
    return GetChapters200ResponseToJSONTyped(json, false);
}

export function GetChapters200ResponseToJSONTyped(value?: GetChapters200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ChapterSummaryToJSON)),
    };
}

