/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { Chapter } from './Chapter';
import {
    ChapterFromJSON,
    ChapterFromJSONTyped,
    ChapterToJSON,
    ChapterToJSONTyped,
} from './Chapter';

/**
 * 
 * @export
 * @interface GetChapter200Response
 */
export interface GetChapter200Response {
    /**
     * 
     * @type {Chapter}
     * @memberof GetChapter200Response
     */
    data: Chapter;
    /**
     * 
     * @type {Meta}
     * @memberof GetChapter200Response
     */
    meta: Meta;
}

/**
 * Check if a given object implements the GetChapter200Response interface.
 */
export function instanceOfGetChapter200Response(value: object): value is GetChapter200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function GetChapter200ResponseFromJSON(json: any): GetChapter200Response {
    return GetChapter200ResponseFromJSONTyped(json, false);
}

export function GetChapter200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetChapter200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ChapterFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
    };
}

export function GetChapter200ResponseToJSON(json: any): GetChapter200Response {
    return GetChapter200ResponseToJSONTyped(json, false);
}

export function GetChapter200ResponseToJSONTyped(value?: GetChapter200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ChapterToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
    };
}

