/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { Section } from './Section';
import {
    SectionFromJSON,
    SectionFromJSONTyped,
    SectionToJSON,
    SectionToJSONTyped,
} from './Section';

/**
 * 
 * @export
 * @interface GetSection200Response
 */
export interface GetSection200Response {
    /**
     * 
     * @type {Section}
     * @memberof GetSection200Response
     */
    data: Section;
    /**
     * 
     * @type {Meta}
     * @memberof GetSection200Response
     */
    meta: Meta;
}

/**
 * Check if a given object implements the GetSection200Response interface.
 */
export function instanceOfGetSection200Response(value: object): value is GetSection200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function GetSection200ResponseFromJSON(json: any): GetSection200Response {
    return GetSection200ResponseFromJSONTyped(json, false);
}

export function GetSection200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSection200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': SectionFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
    };
}

export function GetSection200ResponseToJSON(json: any): GetSection200Response {
    return GetSection200ResponseToJSONTyped(json, false);
}

export function GetSection200ResponseToJSONTyped(value?: GetSection200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': SectionToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
    };
}

