/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerseSummary } from './VerseSummary';
import {
    VerseSummaryFromJSON,
    VerseSummaryFromJSONTyped,
    VerseSummaryToJSON,
    VerseSummaryToJSONTyped,
} from './VerseSummary';

/**
 * 
 * @export
 * @interface GetVerses200Response
 */
export interface GetVerses200Response {
    /**
     * 
     * @type {Array<VerseSummary>}
     * @memberof GetVerses200Response
     */
    data: Array<VerseSummary>;
}

/**
 * Check if a given object implements the GetVerses200Response interface.
 */
export function instanceOfGetVerses200Response(value: object): value is GetVerses200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetVerses200ResponseFromJSON(json: any): GetVerses200Response {
    return GetVerses200ResponseFromJSONTyped(json, false);
}

export function GetVerses200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVerses200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(VerseSummaryFromJSON)),
    };
}

export function GetVerses200ResponseToJSON(json: any): GetVerses200Response {
    return GetVerses200ResponseToJSONTyped(json, false);
}

export function GetVerses200ResponseToJSONTyped(value?: GetVerses200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(VerseSummaryToJSON)),
    };
}

