/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { Verse } from './Verse';
import {
    VerseFromJSON,
    VerseFromJSONTyped,
    VerseToJSON,
    VerseToJSONTyped,
} from './Verse';

/**
 * 
 * @export
 * @interface GetVerse200Response
 */
export interface GetVerse200Response {
    /**
     * 
     * @type {Verse}
     * @memberof GetVerse200Response
     */
    data: Verse;
    /**
     * 
     * @type {Meta}
     * @memberof GetVerse200Response
     */
    meta: Meta;
}

/**
 * Check if a given object implements the GetVerse200Response interface.
 */
export function instanceOfGetVerse200Response(value: object): value is GetVerse200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function GetVerse200ResponseFromJSON(json: any): GetVerse200Response {
    return GetVerse200ResponseFromJSONTyped(json, false);
}

export function GetVerse200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVerse200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': VerseFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
    };
}

export function GetVerse200ResponseToJSON(json: any): GetVerse200Response {
    return GetVerse200ResponseToJSONTyped(json, false);
}

export function GetVerse200ResponseToJSONTyped(value?: GetVerse200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': VerseToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
    };
}

