/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Language
 */
export interface Language {
    /**
     * 
     * @type {string}
     * @memberof Language
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Language
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Language
     */
    nameLocal: string;
    /**
     * 
     * @type {string}
     * @memberof Language
     */
    script: string;
    /**
     * 
     * @type {string}
     * @memberof Language
     */
    scriptDirection: string;
}

/**
 * Check if a given object implements the Language interface.
 */
export function instanceOfLanguage(value: object): value is Language {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('nameLocal' in value) || value['nameLocal'] === undefined) return false;
    if (!('script' in value) || value['script'] === undefined) return false;
    if (!('scriptDirection' in value) || value['scriptDirection'] === undefined) return false;
    return true;
}

export function LanguageFromJSON(json: any): Language {
    return LanguageFromJSONTyped(json, false);
}

export function LanguageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Language {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'nameLocal': json['nameLocal'],
        'script': json['script'],
        'scriptDirection': json['scriptDirection'],
    };
}

export function LanguageToJSON(json: any): Language {
    return LanguageToJSONTyped(json, false);
}

export function LanguageToJSONTyped(value?: Language | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'nameLocal': value['nameLocal'],
        'script': value['script'],
        'scriptDirection': value['scriptDirection'],
    };
}

