/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { SearchResponse } from './SearchResponse';
import {
    SearchResponseFromJSON,
    SearchResponseFromJSONTyped,
    SearchResponseToJSON,
    SearchResponseToJSONTyped,
} from './SearchResponse';

/**
 * 
 * @export
 * @interface SearchBible200Response
 */
export interface SearchBible200Response {
    /**
     * 
     * @type {string}
     * @memberof SearchBible200Response
     */
    query?: string;
    /**
     * 
     * @type {SearchResponse}
     * @memberof SearchBible200Response
     */
    data: SearchResponse;
    /**
     * 
     * @type {Meta}
     * @memberof SearchBible200Response
     */
    meta: Meta;
}

/**
 * Check if a given object implements the SearchBible200Response interface.
 */
export function instanceOfSearchBible200Response(value: object): value is SearchBible200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function SearchBible200ResponseFromJSON(json: any): SearchBible200Response {
    return SearchBible200ResponseFromJSONTyped(json, false);
}

export function SearchBible200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchBible200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'] == null ? undefined : json['query'],
        'data': SearchResponseFromJSON(json['data']),
        'meta': MetaFromJSON(json['meta']),
    };
}

export function SearchBible200ResponseToJSON(json: any): SearchBible200Response {
    return SearchBible200ResponseToJSONTyped(json, false);
}

export function SearchBible200ResponseToJSONTyped(value?: SearchBible200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
        'data': SearchResponseToJSON(value['data']),
        'meta': MetaToJSON(value['meta']),
    };
}

