/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SectionNext
 */
export interface SectionNext {
    /**
     * 
     * @type {string}
     * @memberof SectionNext
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SectionNext
     */
    title?: string;
}

/**
 * Check if a given object implements the SectionNext interface.
 */
export function instanceOfSectionNext(value: object): value is SectionNext {
    return true;
}

export function SectionNextFromJSON(json: any): SectionNext {
    return SectionNextFromJSONTyped(json, false);
}

export function SectionNextFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionNext {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function SectionNextToJSON(json: any): SectionNext {
    return SectionNextToJSONTyped(json, false);
}

export function SectionNextToJSONTyped(value?: SectionNext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
    };
}

