/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SectionNext } from './SectionNext';
import {
    SectionNextFromJSON,
    SectionNextFromJSONTyped,
    SectionNextToJSON,
    SectionNextToJSONTyped,
} from './SectionNext';

/**
 * 
 * @export
 * @interface Section
 */
export interface Section {
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    bibleId: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    bookId: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    chapterId: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    content: string;
    /**
     * 
     * @type {number}
     * @memberof Section
     */
    verseCount: number;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    firstVerseId: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    lastVerseId: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    firstVerseOrgId: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    lastVerseOrgId: string;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    copyright: string;
    /**
     * 
     * @type {SectionNext}
     * @memberof Section
     */
    next?: SectionNext;
    /**
     * 
     * @type {SectionNext}
     * @memberof Section
     */
    previous?: SectionNext;
}

/**
 * Check if a given object implements the Section interface.
 */
export function instanceOfSection(value: object): value is Section {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('bibleId' in value) || value['bibleId'] === undefined) return false;
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    if (!('chapterId' in value) || value['chapterId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('verseCount' in value) || value['verseCount'] === undefined) return false;
    if (!('firstVerseId' in value) || value['firstVerseId'] === undefined) return false;
    if (!('lastVerseId' in value) || value['lastVerseId'] === undefined) return false;
    if (!('firstVerseOrgId' in value) || value['firstVerseOrgId'] === undefined) return false;
    if (!('lastVerseOrgId' in value) || value['lastVerseOrgId'] === undefined) return false;
    if (!('copyright' in value) || value['copyright'] === undefined) return false;
    return true;
}

export function SectionFromJSON(json: any): Section {
    return SectionFromJSONTyped(json, false);
}

export function SectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Section {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bibleId': json['bibleId'],
        'bookId': json['bookId'],
        'chapterId': json['chapterId'],
        'title': json['title'],
        'content': json['content'],
        'verseCount': json['verseCount'],
        'firstVerseId': json['firstVerseId'],
        'lastVerseId': json['lastVerseId'],
        'firstVerseOrgId': json['firstVerseOrgId'],
        'lastVerseOrgId': json['lastVerseOrgId'],
        'copyright': json['copyright'],
        'next': json['next'] == null ? undefined : SectionNextFromJSON(json['next']),
        'previous': json['previous'] == null ? undefined : SectionNextFromJSON(json['previous']),
    };
}

export function SectionToJSON(json: any): Section {
    return SectionToJSONTyped(json, false);
}

export function SectionToJSONTyped(value?: Section | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bibleId': value['bibleId'],
        'bookId': value['bookId'],
        'chapterId': value['chapterId'],
        'title': value['title'],
        'content': value['content'],
        'verseCount': value['verseCount'],
        'firstVerseId': value['firstVerseId'],
        'lastVerseId': value['lastVerseId'],
        'firstVerseOrgId': value['firstVerseOrgId'],
        'lastVerseOrgId': value['lastVerseOrgId'],
        'copyright': value['copyright'],
        'next': SectionNextToJSON(value['next']),
        'previous': SectionNextToJSON(value['previous']),
    };
}

