/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SectionSummary
 */
export interface SectionSummary {
    /**
     * 
     * @type {string}
     * @memberof SectionSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SectionSummary
     */
    bibleId: string;
    /**
     * 
     * @type {string}
     * @memberof SectionSummary
     */
    bookId: string;
    /**
     * 
     * @type {string}
     * @memberof SectionSummary
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SectionSummary
     */
    firstVerseId: string;
    /**
     * 
     * @type {string}
     * @memberof SectionSummary
     */
    lastVerseId: string;
    /**
     * 
     * @type {string}
     * @memberof SectionSummary
     */
    firstVerseOrgId: string;
    /**
     * 
     * @type {string}
     * @memberof SectionSummary
     */
    lastVerseOrgId: string;
}

/**
 * Check if a given object implements the SectionSummary interface.
 */
export function instanceOfSectionSummary(value: object): value is SectionSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('bibleId' in value) || value['bibleId'] === undefined) return false;
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('firstVerseId' in value) || value['firstVerseId'] === undefined) return false;
    if (!('lastVerseId' in value) || value['lastVerseId'] === undefined) return false;
    if (!('firstVerseOrgId' in value) || value['firstVerseOrgId'] === undefined) return false;
    if (!('lastVerseOrgId' in value) || value['lastVerseOrgId'] === undefined) return false;
    return true;
}

export function SectionSummaryFromJSON(json: any): SectionSummary {
    return SectionSummaryFromJSONTyped(json, false);
}

export function SectionSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SectionSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bibleId': json['bibleId'],
        'bookId': json['bookId'],
        'title': json['title'],
        'firstVerseId': json['firstVerseId'],
        'lastVerseId': json['lastVerseId'],
        'firstVerseOrgId': json['firstVerseOrgId'],
        'lastVerseOrgId': json['lastVerseOrgId'],
    };
}

export function SectionSummaryToJSON(json: any): SectionSummary {
    return SectionSummaryToJSONTyped(json, false);
}

export function SectionSummaryToJSONTyped(value?: SectionSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bibleId': value['bibleId'],
        'bookId': value['bookId'],
        'title': value['title'],
        'firstVerseId': value['firstVerseId'],
        'lastVerseId': value['lastVerseId'],
        'firstVerseOrgId': value['firstVerseOrgId'],
        'lastVerseOrgId': value['lastVerseOrgId'],
    };
}

