/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerseNext
 */
export interface VerseNext {
    /**
     * 
     * @type {string}
     * @memberof VerseNext
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof VerseNext
     */
    bookId?: string;
}

/**
 * Check if a given object implements the VerseNext interface.
 */
export function instanceOfVerseNext(value: object): value is VerseNext {
    return true;
}

export function VerseNextFromJSON(json: any): VerseNext {
    return VerseNextFromJSONTyped(json, false);
}

export function VerseNextFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerseNext {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'bookId': json['bookId'] == null ? undefined : json['bookId'],
    };
}

export function VerseNextToJSON(json: any): VerseNext {
    return VerseNextToJSONTyped(json, false);
}

export function VerseNextToJSONTyped(value?: VerseNext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'bookId': value['bookId'],
    };
}

