/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerseSummary
 */
export interface VerseSummary {
    /**
     * 
     * @type {string}
     * @memberof VerseSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof VerseSummary
     */
    orgId: string;
    /**
     * 
     * @type {string}
     * @memberof VerseSummary
     */
    bibleId: string;
    /**
     * 
     * @type {string}
     * @memberof VerseSummary
     */
    bookId: string;
    /**
     * 
     * @type {string}
     * @memberof VerseSummary
     */
    chapterId: string;
    /**
     * 
     * @type {string}
     * @memberof VerseSummary
     */
    reference: string;
}

/**
 * Check if a given object implements the VerseSummary interface.
 */
export function instanceOfVerseSummary(value: object): value is VerseSummary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('orgId' in value) || value['orgId'] === undefined) return false;
    if (!('bibleId' in value) || value['bibleId'] === undefined) return false;
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    if (!('chapterId' in value) || value['chapterId'] === undefined) return false;
    if (!('reference' in value) || value['reference'] === undefined) return false;
    return true;
}

export function VerseSummaryFromJSON(json: any): VerseSummary {
    return VerseSummaryFromJSONTyped(json, false);
}

export function VerseSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerseSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'orgId': json['orgId'],
        'bibleId': json['bibleId'],
        'bookId': json['bookId'],
        'chapterId': json['chapterId'],
        'reference': json['reference'],
    };
}

export function VerseSummaryToJSON(json: any): VerseSummary {
    return VerseSummaryToJSONTyped(json, false);
}

export function VerseSummaryToJSONTyped(value?: VerseSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'orgId': value['orgId'],
        'bibleId': value['bibleId'],
        'bookId': value['bookId'],
        'chapterId': value['chapterId'],
        'reference': value['reference'],
    };
}

