/* tslint:disable */
/* eslint-disable */
/**
 * API.Bible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetVerse200Response,
  GetVerses200Response,
} from '../models/index';
import {
    GetVerse200ResponseFromJSON,
    GetVerse200ResponseToJSON,
    GetVerses200ResponseFromJSON,
    GetVerses200ResponseToJSON,
} from '../models/index';

export interface GetVerseRequest {
    bibleId: string;
    verseId: string;
    contentType?: GetVerseContentTypeEnum;
    includeNotes?: boolean;
    includeTitles?: boolean;
    includeChapterNumbers?: boolean;
    includeVerseNumbers?: boolean;
    includeVerseSpans?: boolean;
    parallels?: string;
    useOrgId?: boolean;
}

export interface GetVersesRequest {
    bibleId: string;
    chapterId: string;
}

/**
 * 
 */
export class VersesApi extends runtime.BaseAPI {

    /**
     * Gets a `Verse` object for a given `bibleId` and `verseId`. This Verse object also includes an `content` property with the verse corresponding to the verseId. 
     */
    async getVerseRaw(requestParameters: GetVerseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetVerse200Response>> {
        if (requestParameters['bibleId'] == null) {
            throw new runtime.RequiredError(
                'bibleId',
                'Required parameter "bibleId" was null or undefined when calling getVerse().'
            );
        }

        if (requestParameters['verseId'] == null) {
            throw new runtime.RequiredError(
                'verseId',
                'Required parameter "verseId" was null or undefined when calling getVerse().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['contentType'] != null) {
            queryParameters['content-type'] = requestParameters['contentType'];
        }

        if (requestParameters['includeNotes'] != null) {
            queryParameters['include-notes'] = requestParameters['includeNotes'];
        }

        if (requestParameters['includeTitles'] != null) {
            queryParameters['include-titles'] = requestParameters['includeTitles'];
        }

        if (requestParameters['includeChapterNumbers'] != null) {
            queryParameters['include-chapter-numbers'] = requestParameters['includeChapterNumbers'];
        }

        if (requestParameters['includeVerseNumbers'] != null) {
            queryParameters['include-verse-numbers'] = requestParameters['includeVerseNumbers'];
        }

        if (requestParameters['includeVerseSpans'] != null) {
            queryParameters['include-verse-spans'] = requestParameters['includeVerseSpans'];
        }

        if (requestParameters['parallels'] != null) {
            queryParameters['parallels'] = requestParameters['parallels'];
        }

        if (requestParameters['useOrgId'] != null) {
            queryParameters['use-org-id'] = requestParameters['useOrgId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/bibles/{bibleId}/verses/{verseId}`;
        urlPath = urlPath.replace(`{${"bibleId"}}`, encodeURIComponent(String(requestParameters['bibleId'])));
        urlPath = urlPath.replace(`{${"verseId"}}`, encodeURIComponent(String(requestParameters['verseId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetVerse200ResponseFromJSON(jsonValue));
    }

    /**
     * Gets a `Verse` object for a given `bibleId` and `verseId`. This Verse object also includes an `content` property with the verse corresponding to the verseId. 
     */
    async getVerse(requestParameters: GetVerseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetVerse200Response> {
        const response = await this.getVerseRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Gets an array of `Verse` objects for a given `bibleId` and `chapterId` 
     */
    async getVersesRaw(requestParameters: GetVersesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetVerses200Response>> {
        if (requestParameters['bibleId'] == null) {
            throw new runtime.RequiredError(
                'bibleId',
                'Required parameter "bibleId" was null or undefined when calling getVerses().'
            );
        }

        if (requestParameters['chapterId'] == null) {
            throw new runtime.RequiredError(
                'chapterId',
                'Required parameter "chapterId" was null or undefined when calling getVerses().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["api-key"] = await this.configuration.apiKey("api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/bibles/{bibleId}/chapters/{chapterId}/verses`;
        urlPath = urlPath.replace(`{${"bibleId"}}`, encodeURIComponent(String(requestParameters['bibleId'])));
        urlPath = urlPath.replace(`{${"chapterId"}}`, encodeURIComponent(String(requestParameters['chapterId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetVerses200ResponseFromJSON(jsonValue));
    }

    /**
     * Gets an array of `Verse` objects for a given `bibleId` and `chapterId` 
     */
    async getVerses(requestParameters: GetVersesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetVerses200Response> {
        const response = await this.getVersesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetVerseContentTypeEnum = {
    Html: 'html',
    Json: 'json',
    Text: 'text'
} as const;
export type GetVerseContentTypeEnum = typeof GetVerseContentTypeEnum[keyof typeof GetVerseContentTypeEnum];
